export const operations = {
  POWER: "^",
  ADDITION: "+",
  SUBTRACTION: "-",
  MULTIPLICATION: "*",
  DIVISION: "/",
  FACTORIAL: "!",
  SIN: "sin",
  COS: "cos",
  TG: "tg",
  CTG: "ctg",
  SQR: "sqr",
  SQRT: "sqrt",
  TRUNC: "trunc",
  ROUND: "round",
  BRACKETS: "()",
  SQUARE_INLINE: "**",
  DOUBLE_SUBTRACTION: "--",
  UNSUPPORTED_OPERATION: "unsupported",
};
