export const actionTypes = {
  INIT_FIELD: "INIT_FIELD",
  INIT_FIELD_PERFORMED: "INIT_FIELD_PERFORMED",
  CHANGE_SETTING: "CHANGE_SETTING",
  SAGA_CHANGE_SETTING: "SAGA_CHANGE_SETTING",
  USER_LOGIN: "user/USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
};
